server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billboards_ad?autoreconnect=true
    username: root
    password: root_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    enabled: true
    user: root
    password: root_password
    url: jdbc:mysql://localhost:3306/billboards_ad
    schemas: billboards_ad

abstract-storage:
  advertising: abstract_storage/advertising
  logs: abstract_storage/logs
  schedule: abstract_storage/schedule