server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billboards_ad
    username: root
    password: root_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
